version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
<<<<<<< HEAD
            docker build -t chauhanhimani/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push chauhanhimani/todo-app:$version
=======
            docker build -t rlncts/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push rlncts/todo-app:$version
>>>>>>> a5572052f08594e9dd9ebd6965c8351f1806ea7e

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
<<<<<<< HEAD
            git clone https://github.com/chauhan-himani/kube_manifest.git
            git config --global user.email "chauhanhimani512@gmail.com"
            git config --global user.name "chauhan-himani"
=======
            git clone https://github.com/laks-narasimman/kube_manifest.git
            git config --global user.email "jainarasimma123@gmail.com"
            git config --global user.name "laks-narasimman"
>>>>>>> a5572052f08594e9dd9ebd6965c8351f1806ea7e
            pwd
            cd kube_manifest
            pwd
            echo $TAG
            sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
            cat manifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
<<<<<<< HEAD
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/chauhan-himani/kube_manifest.git main 
=======
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/laks-narasimman/kube_manifest.git main 
>>>>>>> a5572052f08594e9dd9ebd6965c8351f1806ea7e
workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - Update_manifest:
          requires:
            - build_and_push
      
<<<<<<< HEAD


=======
>>>>>>> a5572052f08594e9dd9ebd6965c8351f1806ea7e
